sudo: required
dist: trusty
os: linux
language: minimal
cache:
  ccache: true
  directories:
  - depends/built
  - depends/sdk-sources
  - $HOME/.ccache
stages:
  - lint
  - test
env:
  global:
    - MAKEJOBS=-j3
    - RUN_UNIT_TESTS=false # TODO Fix tests
    - RUN_FUNCTIONAL_TESTS=false # Not Yet Implemented
    - RUN_BENCH=false  # Set to true for any one job that has debug enabled, to quickly check bench is not crashing or hitting assertions
    - DOCKER_NAME_TAG=ubuntu:18.04
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CCACHE_DIR=$HOME/.ccache
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
    - WINEDEBUG=fixme-all
    - DOCKER_PACKAGES="build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache"

before_install:
  - set -o errexit; source .travis/test_03_before_install.sh
install:
  - set -o errexit; source .travis/test_04_install.sh
before_script:
  - set -o errexit; source .travis/test_05_before_script.sh
script:
  - set -o errexit; source .travis/test_06_script.sh
after_script:
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG

jobs:
  include:

  # arm
  - stage: test
    name: arm
    env: >-
      HOST=arm-linux-gnueabihf
      PACKAGES="python3 g++-arm-linux-gnueabihf"
      DEP_OPTS="NO_QT=1"
      CHECK_DOC=0
      GOAL="install"
      # -Wno-psabi is to disable ABI warnings: "note: parameter passing for argument of type ... changed in GCC 7.1"
      # This could be removed once the ABI change warning does not show up by default
      BITCOIN_CONFIG="--without-gui --enable-glibc-back-compat --enable-reduce-exports CXXFLAGS=-Wno-psabi"

  # win32
  - stage: test
    name: win32
    env: >-
      HOST=i686-w64-mingw32
      DPKG_ADD_ARCH="i386"
      DEP_OPTS="NO_QT=0"
      PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc"
      GOAL="install"
      BITCOIN_CONFIG="--enable-gui --enable-reduce-exports"

  # win64
  - stage: test
    name: win64
    env: >-
      HOST=x86_64-w64-mingw32
      DPKG_ADD_ARCH="i386"
      DEP_OPTS="NO_QT=1"
      PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc"
      GOAL="install"
      BITCOIN_CONFIG="--without-gui --enable-reduce-exports --disable-gui-tests"

  # linux32
  - stage: test
    name: linux32
    env: >-
      HOST=i686-pc-linux-gnu
      PACKAGES="g++-multilib bc python3-zmq"
      DEP_OPTS="NO_QT=1"
      GOAL="install"
      USE_SHELL="/bin/dash"
      PYZMQ=true
      BITCOIN_CONFIG="--without-gui --enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"

  # linux64
  - stage: test
    name: linux64
    env: >-
      HOST=x86_64-unknown-linux-gnu
      PACKAGES="bc python3-zmq"
      DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1"
      GOAL="install"
      PYZMQ=true
      BITCOIN_CONFIG="--without-gui --enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER"

  # mac64
  - stage: test
    name: mac64
    env: >-
      HOST=x86_64-apple-darwin14
      PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev python3-setuptools-git"
      DEP_OPTS="NO_QT=1"
      OSX_SDK=10.11
      GOAL="install"
      BITCOIN_CONFIG="--without-gui --enable-reduce-exports"
